################################################################################
#
# librdkafka
#
################################################################################

LIBRDKAFKA_VERSION = 2.13.2
LIBRDKAFKA_SITE = $(call github,confluentinc,librdkafka,v$(LIBRDKAFKA_VERSION))
LIBRDKAFKA_LICENSE = BSD-2-Clause
LIBRDKAFKA_LICENSE_FILES = LICENSES.txt
LIBRDKAFKA_INSTALL_STAGING = YES
LIBRDKAFKA_DEPENDENCIES = lz4
LIBRDKAFKA_CONF_OPTS = \
	-DRDKAFKA_BUILD_EXAMPLES=OFF \
	-DRDKAFKA_BUILD_TESTS=OFF

ifeq ($(BR2_STATIC_LIBS),y)
LIBRDKAFKA_CONF_OPTS += -DRDKAFKA_BUILD_STATIC=ON
else
LIBRDKAFKA_CONF_OPTS += -DRDKAFKA_BUILD_STATIC=OFF
endif

ifeq ($(BR2_PACKAGE_ZLIB),y)
LIBRDKAFKA_CONF_OPTS += -DWITH_ZLIB=ON
LIBRDKAFKA_DEPENDENCIES += zlib
else
LIBRDKAFKA_CONF_OPTS += -DWITH_ZLIB=OFF
endif

ifeq ($(BR2_PACKAGE_LIBCURL),y)
LIBRDKAFKA_CONF_OPTS += -DWITH_CURL=ON
LIBRDKAFKA_DEPENDENCIES += libcurl
else
LIBRDKAFKA_CONF_OPTS += -DWITH_CURL=OFF
endif

ifeq ($(BR2_PACKAGE_ZSTD),y)
LIBRDKAFKA_CONF_OPTS += -DWITH_ZSTD=ON
LIBRDKAFKA_DEPENDENCIES += zstd
else
LIBRDKAFKA_CONF_OPTS += -DWITH_ZSTD=OFF
endif

ifeq ($(BR2_PACKAGE_OPENSSL),y)
LIBRDKAFKA_CONF_OPTS += -DWITH_SSL=ON
LIBRDKAFKA_DEPENDENCIES += openssl
else
LIBRDKAFKA_CONF_OPTS += -DWITH_SSL=OFF
endif

$(eval $(cmake-package))
