#!/bin/sh

case "$1" in
start)
	printf "Loading kernel modules: "
	for conf in /etc/modules-load.d/*.conf; do
		[ -f "$conf" ] || continue
		while read -r module args; do
			case "$module" in
			""|\#*) continue ;;
			esac
			modprobe $module $args
		done < "$conf"
	done
	echo "done."
	;;
*)
	;;
esac
